'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const I=require('../sleep-insights.js');
const NOW=new Date(2026,9,5,22);
// Synthetic regression fixtures only. Never commit personal health exports.
function night(d='2026-10-04',extra={}){return {d,on:300,off:800,tst:480,core:300,deep:80,rem:100,awake:20,unspec:0,hr:55,hrv:60,...extra};}
function history(){return Array.from({length:10},(_,i)=>night(I.shiftDay('2026-10-04',-i-1)));}
function summary(n=night(),settings={}){return I.summarize(n,[...history(),n],settings,NOW);}
test('8h+ with 32m blank keeps recorded duration, deep and HRV deltas',()=>{const n=night(undefined,{tst:520,core:320,deep:85,rem:115,off:872}),s=summary(n);assert.equal(s.durationMinutes,520);assert.equal(s.unrecordedMinutes,32);assert.equal(s.awakeMinutes,20);assert.equal(s.delta.hrv,0);assert.ok(s.stages.valid);assert.notEqual(s.quality.label,'记录不完整');assert.equal(s.quality.signals.fragmented,false);assert.match(s.quality.warnings.join(' '),/32分钟/);});
test('no 30-minute discontinuity, large gaps reduce confidence not visibility',()=>{for(const gap of [0,29,30,31,32,60,120,240]){const n=night(undefined,{off:800+gap}),s=summary(n);assert.equal(I.latestNight([n],NOW),n);assert.equal(s.unrecordedMinutes,gap);assert.equal(s.delta.deepPct,0);assert.equal(s.delta.hrv,0);assert.notEqual(s.quality.label,'记录不完整');if(gap>=60)assert.equal(s.quality.label,'已记录部分较平稳');}});
test('long sleep with lower deep percentage and lower HRV is not rescued by more deep minutes',()=>{const s=summary(night(undefined,{tst:690,core:388,deep:82,rem:220,awake:10,off:1000,hrv:35}));assert.equal(s.quality.label,'睡得久，恢复信号偏弱');assert.equal(s.quality.tone,'warn');assert.ok(s.delta.deepMinutes>0);assert.ok(s.delta.deepPct<0);assert.equal(s.quality.signals.deepLow,true);assert.equal(s.quality.signals.hrvLow,true);});
test('high HRV cannot cancel lower deep proportion',()=>{const s=summary(night(undefined,{core:330,deep:50,hrv:120}));assert.equal(s.quality.signals.deepLow,true);assert.equal(s.quality.tone,'warn');assert.equal(s.quality.signals.hrvLow,false);});
test('more deep sleep cannot cancel low HRV',()=>{const s=summary(night(undefined,{core:270,deep:110,hrv:40}));assert.equal(s.quality.signals.hrvLow,true);assert.equal(s.quality.label,'恢复信号偏弱');});
test('sleep HR independently flags without diagnosing disease',()=>{const s=summary(night(undefined,{hr:65}));assert.equal(s.quality.signals.hrVeryHigh,true);assert.equal(s.quality.tone,'warn');assert.doesNotMatch(s.quality.summary,/感染|心脏病|发热/);});
test('tired feedback changes verdict; positive feedback does not erase adverse metrics',()=>{assert.equal(summary(night(),{feeling:'tired'}).quality.label,'睡后仍然困倦');const s=summary(night(undefined,{hrv:35}),{feeling:'good'});assert.equal(s.quality.tone,'warn');assert.match(s.quality.summary,/体感不错/);});
test('long sleep alone does not earn a good recovery result',()=>{const s=summary(night(undefined,{tst:650,core:400,deep:110,rem:140,awake:20,off:970}));assert.equal(s.quality.label,'睡得偏长，留意是否解乏');assert.notEqual(s.quality.tone,'good');});
test('HRV zero, negative, NaN and null never become low-recovery readings',()=>{for(const hrv of [0,-1,NaN,null]){const s=summary(night(undefined,{hrv}));assert.equal(s.delta.hrv,null);assert.equal(s.quality.signals.hrvLow,false);assert.notEqual(s.quality.tone,'good');}});
test('unspecified sleep and unrecorded gaps use distinct denominators',()=>{const s=summary(night(undefined,{core:240,deep:60,rem:60,unspec:120}));assert.equal(s.stages.coverage,75);assert.equal(s.stages.deepPct,16.7);assert.equal(s.stages.confirmedDeepPct,12.5);assert.equal(s.unrecordedMinutes,0);assert.equal(s.delta.deepPct,null);assert.equal(s.delta.hrv,0);assert.notEqual(s.quality.tone,'good');});
test('product cutoffs are explicit, with all input data left untouched',()=>{const n=night(),h=history(),settings={wake:540},before=JSON.stringify([n,h,settings]);const s=I.summarize(n,h,settings,NOW);assert.equal(JSON.stringify([n,h,settings]),before);assert.match(s.quality.method,/不是临床诊断界值/);assert.equal(summary(night(undefined,{hrv:48})).quality.signals.hrvLow,true);assert.equal(summary(night(undefined,{hrv:49})).quality.signals.hrvLow,false);assert.equal(summary(night(undefined,{hr:60})).quality.signals.hrHigh,true);});
